export const PERMISSIONS = Object.freeze({
    AGREGAR_CONTACTO: 'add_contact',
    EDITAR_CONTACTO: 'change_contact',
    VER_CONTACTO: 'view_contact',

    AGREGAR_EMPRESA: 'add_company',
    EDITAR_EMPRESA: 'change_company',
    VER_EMPRESA: 'view_company',

    AGREGAR_PROGRAMA: 'add_program',
    EDITAR_PROGRAMA: 'change_program',
    VER_PROGRAMA: 'view_program',

    AGREGAR_ESTUDIANTE: 'add_student',
    EDITAR_ESTUDIANTE: 'change_student',
    VER_ESTUDIANTE: 'view_student',

    AGREGAR_CONVENIO: 'add_agreement',
    EDITAR_CONVENIO: 'change_agreement',
    VER_CONVENIO: 'view_agreement',
    CAMBIAR_ESTADO_CONVENIO: 'toggle_status',

    AGREGAR_ESTUDIANTE_CONVENIO: 'add_agreementstudentthrough',
    VER_ESTUDIANTE_CONVENIO: 'view_agreementstudentthrough',

    CREAR_DOCUMENTO_DE_CONVENIO: 'add_documentagreement',
    EDITAR_DOCUMENTO_DE_CONVENIO: 'change_documentagreement',
    VER_DOCUMENTO_DE_CONVENIO: 'view_documentagreement',
    CAMBIAR_ESTADO_DOCUMENTO: 'toggle_status_document',

    AGREGAR_DOCUMENTO_A_CONVENIO: 'add_agreementdocumentthrough',
    EDITAR_DOCUMENTO_A_CONVENIO: 'change_agreementdocumentthrough',
    VER_DOCUMENTO_A_CONVENIO: 'view_agreementdocumentthrough',

    AGREGAR_DOCUMENTO_PRACTICA: 'add_documentpractice',
    EDITAR_DOCUMENTO_PRACTICA: 'change_documentpractice',
    VER_DOCUMENTO_PRACTICA: 'view_documentpractice',

    AGREGAR_SEGUIMIENTO: 'add_internshiptracking',
    EDITAR_SEGUIMIENTO: 'change_internshiptracking',
    VER_SEGUIMIENTO: 'view_internshiptracking',

    AGREGAR_OFERTA_PRACTICA: 'add_practicaloffer',
    EDITAR_OFERTA_PRACTICA: 'change_practicaloffer',
    VER_OFERTA_PRACTICA: 'view_practicaloffer',
    
    AGREGAR_DOCENTE: 'add_teacher',
    EDITAR_DOCENTE: 'change_teacher',
    VER_DOCENTE: 'view_teacher',

    AGREGAR_SUSTENTACION: 'add_defense',
    EDITAR_SUSTENTACION: 'change_defense',
    VER_SUSTENTACION: 'view_defense',
    FINALIZAR_SUSTENTACION: 'finish_defense',

    AGREGAR_COMENTARIO_SUSTENTACION: 'add_defensecomment',
    EDITAR_COMENTARIO_SUSTENTACION: 'change_defensecomment',
    VER_COMENTARIO_SUSTENTACION: 'view_defensecomment',

    AGREGAR_PRACTICA: 'add_practice', 
    EDITAR_PRACTICA: 'add_practice', 
    VER_PRACTICA: 'add_practice', 

})

export const PERMISSIONS_TRANSLATE = Object.freeze({
  add_logentry: "Puede agregar entrada de registro",
  change_logentry: "Puede cambiar entrada de registro",
  delete_logentry: "Puede eliminar entrada de registro",
  view_logentry: "Puede ver entrada de registro",
  add_permission: "Puede agregar permiso",
  change_permission: "Puede cambiar permiso",
  delete_permission: "Puede eliminar permiso",
  view_permission: "Puede ver permiso",
  add_group: "Puede agregar grupo",
  change_group: "Puede cambiar grupo",
  delete_group: "Puede eliminar grupo",
  view_group: "Puede ver grupo",
  add_contenttype: "Puede agregar tipo de contenido",
  change_contenttype: "Puede cambiar tipo de contenido",
  delete_contenttype: "Puede eliminar tipo de contenido",
  view_contenttype: "Puede ver tipo de contenido",
  add_session: "Puede agregar sesión",
  change_session: "Puede cambiar sesión",
  delete_session: "Puede eliminar sesión",
  view_session: "Puede ver sesión",
  add_customuser: "Puede agregar Usuario",
  change_customuser: "Puede cambiar Usuario",
  delete_customuser: "Puede eliminar Usuario",
  view_customuser: "Puede ver Usuario",
  set_password: "Puede cambiar la contraseña de otros usuarios",
  add_blacklistedtoken: "Puede agregar token en lista negra",
  change_blacklistedtoken: "Puede cambiar token en lista negra",
  delete_blacklistedtoken: "Puede eliminar token en lista negra",
  view_blacklistedtoken: "Puede ver token en lista negra",
  add_outstandingtoken: "Puede agregar token pendiente",
  change_outstandingtoken: "Puede cambiar token pendiente",
  delete_outstandingtoken: "Puede eliminar token pendiente",
  view_outstandingtoken: "Puede ver token pendiente",
  add_contact: "Puede agregar contacto",
  change_contact: "Puede cambiar contacto",
  delete_contact: "Puede eliminar contacto",
  view_contact: "Puede ver contacto",
  add_company: "Puede agregar empresa",
  change_company: "Puede cambiar empresa",
  delete_company: "Puede eliminar empresa",
  view_company: "Puede ver empresa",
  add_program: "Puede agregar programa",
  change_program: "Puede cambiar programa",
  delete_program: "Puede eliminar programa",
  view_program: "Puede ver programa",
  add_student: "Puede agregar estudiante",
  change_student: "Puede cambiar estudiante",
  delete_student: "Puede eliminar estudiante",
  view_student: "Puede ver estudiante",
  add_agreement: "Puede agregar convenio",
  change_agreement: "Puede cambiar convenio",
  delete_agreement: "Puede eliminar convenio",
  view_agreement: "Puede ver convenio",
  add_agreementstudentthrough: "Puede agregar convenio-estudiante (relación)",
  change_agreementstudentthrough: "Puede cambiar convenio-estudiante (relación)",
  delete_agreementstudentthrough: "Puede eliminar convenio-estudiante (relación)",
  view_agreementstudentthrough: "Puede ver convenio-estudiante (relación)",
  add_documentagreement: "Puede agregar documento de convenio",
  change_documentagreement: "Puede cambiar documento de convenio",
  delete_documentagreement: "Puede eliminar documento de convenio",
  view_documentagreement: "Puede ver documento de convenio",
  add_agreementdocumentthrough: "Puede agregar convenio-documento (relación)",
  change_agreementdocumentthrough: "Puede cambiar convenio-documento (relación)",
  delete_agreementdocumentthrough: "Puede eliminar convenio-documento (relación)",
  view_agreementdocumentthrough: "Puede ver convenio-documento (relación)",
  add_documentpractice: "Puede agregar documento de práctica",
  change_documentpractice: "Puede cambiar documento de práctica",
  delete_documentpractice: "Puede eliminar documento de práctica",
  view_documentpractice: "Puede ver documento de práctica",
  add_internshiptracking: "Puede agregar seguimiento de práctica",
  change_internshiptracking: "Puede cambiar seguimiento de práctica",
  delete_internshiptracking: "Puede eliminar seguimiento de práctica",
  view_internshiptracking: "Puede ver seguimiento de práctica",
  add_practicalofferstudentthrough: "Puede agregar oferta práctica-estudiante (relación)",
  change_practicalofferstudentthrough: "Puede cambiar oferta práctica-estudiante (relación)",
  delete_practicalofferstudentthrough: "Puede eliminar oferta práctica-estudiante (relación)",
  view_practicalofferstudentthrough: "Puede ver oferta práctica-estudiante (relación)",
  add_practicaloffer: "Puede agregar oferta práctica",
  change_practicaloffer: "Puede cambiar oferta práctica",
  delete_practicaloffer: "Puede eliminar oferta práctica",
  view_practicaloffer: "Puede ver oferta práctica",
  add_practice: "Puede agregar práctica",
  change_practice: "Puede cambiar práctica",
  delete_practice: "Puede eliminar práctica",
  view_practice: "Puede ver práctica",
  add_teacher: "Puede agregar docente",
  change_teacher: "Puede cambiar docente",
  delete_teacher: "Puede eliminar docente",
  view_teacher: "Puede ver docente",
  add_defense: "Puede agregar sustentación",
  change_defense: "Puede cambiar sustentación",
  delete_defense: "Puede eliminar sustentación",
  view_defense: "Puede ver sustentación",
  add_defensestudentthrough: "Puede agregar sustentación-estudiante (relación)",
  change_defensestudentthrough: "Puede cambiar sustentación-estudiante (relación)",
  delete_defensestudentthrough: "Puede eliminar sustentación-estudiante (relación)",
  view_defensestudentthrough: "Puede ver sustentación-estudiante (relación)",
  add_defenseteacherthrough: "Puede agregar sustentación-docente (relación)",
  change_defenseteacherthrough: "Puede cambiar sustentación-docente (relación)",
  delete_defenseteacherthrough: "Puede eliminar sustentación-docente (relación)",
  view_defenseteacherthrough: "Puede ver sustentación-docente (relación)",
  add_agreementdocumentcomment: "Puede agregar comentario a documento de convenio",
  change_agreementdocumentcomment: "Puede cambiar comentario a documento de convenio",
  delete_agreementdocumentcomment: "Puede eliminar comentario a documento de convenio",
  view_agreementdocumentcomment: "Puede ver comentario a documento de convenio",
  add_defensecomment: "Puede agregar comentario a sustentación",
  change_defensecomment: "Puede cambiar comentario a sustentación",
  delete_defensecomment: "Puede eliminar comentario a sustentación",
  view_defensecomment: "Puede ver comentario a sustentación",
  add_documentdefense: "Puede agregar documento de sustentación",
  change_documentdefense: "Puede cambiar documento de sustentación",
  delete_documentdefense: "Puede eliminar documento de sustentación",
  view_documentdefense: "Puede ver documento de sustentación",
  finish_defense: "Finalizar sustentación",
  toggle_status: "Puede cambiar el estado del convenio",
  toggle_status_document: "Puede cambiar el estado del documento"
});
